import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'basis_input_field.dart';

class BaseTextInput extends BasisInputField {
  BaseTextInput({
    Key? key,
    bool autoFocus = false,
    bool enableInteractiveSelection = true,
    bool autocorrect = true,
    bool obscureText = false,
    bool enabled = true,
    bool showClearButton = true,
    String? hintText,
    String? labelText,
    String? helperText,
    String? errorText,
    String? initialValue,
    ValueChanged<String>? onChanged,
    Widget? prefixIcon,
    Widget? suffixIcon,
    Widget? clearIcon,
    VoidCallback? onTap,
    TextEditingController? controller,
    TextInputType? keyboardType,
    FormFieldValidator<String>? validator,
    bool autoValidate = false,
    TextStyle? hintStyle,
    TextStyle? labelStyle,
    TextStyle? counterStyle,
    TextStyle? errorStyle,
    TextStyle? textStyle,
    TextStyle? helperStyle,
    List<TextInputFormatter>? inputFormatter,
    Function(bool hasFocus)? onFocusChange,
    TextInputAction? textInputAction,
    Function(String text)? onFieldSubmitted,
    Function(String?)? onSaved,
    int? maxLength,
    int? maxLines,
    int? minLines,
    int? errorMaxLines,
    int? helperMaxLines,
    FocusNode? focusNode,
    VoidCallback? onClearText,
    ValueKey? textInputKey,
    ToolbarOptions? toolbarOptions,
    InputBorder? border,
    OutlineInputBorder? focusBorder,
    VoidCallback? onEditingComplete,
    EdgeInsets? contentPadding,
    Color? cursorColor,
    EdgeInsets? counterPadding,
    Color? backgroundColor,
    bool isBare = false,
  }) : super(
    key: key,
    autoFocus: autoFocus,
    enableInteractiveSelection: enableInteractiveSelection,
    autocorrect: autocorrect,
    obscureText: obscureText,
    enabled: enabled,
    showClearButton: showClearButton,
    hintText: hintText,
    labelText: labelText,
    helperText: helperText,
    errorText: errorText,
    initialValue: initialValue,
    onChanged: onChanged,
    prefixIcon: prefixIcon,
    suffixIcon: suffixIcon,
    clearIcon: clearIcon,
    onTap: onTap,
    controller: controller,
    keyboardType: keyboardType,
    validator: validator,
    autoValidate: autoValidate,
    hintStyle: hintStyle,
    labelStyle: labelStyle,
    counterStyle: counterStyle,
    errorStyle: errorStyle,
    textStyle: textStyle,
    helperStyle: helperStyle,
    inputFormatter: inputFormatter,
    onFocusChange: onFocusChange,
    textInputAction: textInputAction,
    onFieldSubmitted: onFieldSubmitted,
    onSaved: onSaved,
    maxLength: maxLength,
    maxLines: maxLines,
    minLines: minLines,
    errorMaxLines: errorMaxLines,
    helperMaxLines: helperMaxLines,
    focusNode: focusNode,
    onClearText: onClearText,
    textInputKey: textInputKey,
    toolbarOptions: toolbarOptions,
    border: border,
    focusBorder: focusBorder,
    onEditingComplete: onEditingComplete,
    contentPadding: contentPadding,
    cursorColor: cursorColor,
    counterPadding: counterPadding,
    backgroundColor: backgroundColor,
    isBare: isBare,
  );
}
