import 'package:finful_app/app/theme/colors.dart';
import 'package:finful_app/app/theme/dimens.dart';
import 'package:finful_app/common/constants/dimensions.dart';
import 'package:finful_app/common/widgets/app_input/base_text_input.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

final _kHintStyle = TextStyle(
  fontSize: FinfulDimens.textXs,
  height: FinfulDimens.textXsHeight,
  fontWeight: FontWeight.w300,
  color: FinfulColor.textOpacity50,
);

final _kLabelStyle = TextStyle(
  fontSize: FinfulDimens.textXs,
  height: FinfulDimens.textXsHeight,
  fontWeight: FontWeight.w300,
  color: FinfulColor.textOpacity50,
);

final _kCounterStyle = TextStyle(
  fontSize: FinfulDimens.textXs,
  height: FinfulDimens.textXsHeight,
  fontWeight: FontWeight.w300,
  color: FinfulColor.textOpacity50,
);

final _kHelperStyle = TextStyle(
  fontSize: FinfulDimens.textXs,
  height: FinfulDimens.textXsHeight,
  fontWeight: FontWeight.w300,
  color: FinfulColor.textOpacity50,
);

final _kErrorStyle = TextStyle(
  fontSize: FinfulDimens.textXs,
  height: FinfulDimens.textXsHeight,
  fontWeight: FontWeight.w300,
  color: FinfulColor.danger,
);

const _kTextStyle = TextStyle(
  fontSize: FinfulDimens.textXs,
  height: FinfulDimens.textXsHeight,
  fontWeight: FontWeight.w300,
  color: FinfulColor.white,
);

final _kDisabledTextStyle = TextStyle(
  fontSize: FinfulDimens.textXs,
  height: FinfulDimens.textXsHeight,
  fontWeight: FontWeight.w300,
  color: FinfulColor.textOpacity50,
);

final _kDisabledLabelStyle = TextStyle(
  fontSize: FinfulDimens.textXs,
  height: FinfulDimens.textXsHeight,
  fontWeight: FontWeight.w400,
  color: FinfulColor.textOpacity50,
);

const _kDisabledBgColor = FinfulColor.bgDisabled;
const _kBgColor = FinfulColor.white;

enum FinfulTextInputHeight { sm, md }

const EdgeInsets mdPadding = EdgeInsets.only(
  left: FinfulDimens.md,
  top: Dimens.p_16,
  bottom: Dimens.p_16,
);

const EdgeInsets smPadding = EdgeInsets.only(
  left: FinfulDimens.md,
  top: Dimens.p_13,
  bottom: Dimens.p_13,
);

class FinfulTextInput extends BaseTextInput {
  FinfulTextInput({
    Key? key,
    bool? autoFocus,
    bool? enableInteractiveSelection,
    bool? autocorrect,
    bool? obscureText,
    bool? enabled,
    bool? showClearButton,
    String? hintText,
    String? labelText,
    String? helperText,
    String? errorText,
    String? initialValue,
    ValueChanged<String>? onChanged,
    Widget? prefixIcon,
    Widget? suffixIcon,
    Widget? clearIcon,
    VoidCallback? onTap,
    TextEditingController? controller,
    TextInputType? keyboardType,
    FormFieldValidator<String>? validator,
    bool? autoValidate,
    TextStyle? hintStyle,
    TextStyle? labelStyle,
    TextStyle? counterStyle,
    TextStyle? errorStyle,
    TextStyle? textStyle,
    TextStyle? helperStyle,
    List<TextInputFormatter>? inputFormatter,
    Function(bool hasFocus)? onFocusChange,
    TextInputAction? textInputAction,
    Function(String text)? onFieldSubmitted,
    Function(String?)? onSaved,
    int? maxLength,
    required int maxLines,
    required int minLines,
    int? errorMaxLines,
    int? helperMaxLines,
    FocusNode? focusNode,
    VoidCallback? onClearText,
    ValueKey? textInputKey,
    ToolbarOptions? toolbarOptions,
    VoidCallback? onEditingComplete,
    EdgeInsets? contentPadding,
    Color? cursorColor,
    EdgeInsets? counterPadding,
    Color? backgroundColor,
    bool? isBare,
  }) : super(
    key: key,
    autoFocus: autoFocus ?? false,
    enableInteractiveSelection: enableInteractiveSelection ?? true,
    autocorrect: autocorrect ?? false,
    obscureText: obscureText ?? false,
    enabled: enabled ?? true,
    showClearButton: showClearButton ?? true,
    isBare: isBare ?? false,
    hintText: hintText,
    labelText: labelText,
    helperText: helperText,
    errorText: errorText,
    initialValue: initialValue,
    onChanged: onChanged,
    prefixIcon: prefixIcon,
    suffixIcon: suffixIcon,
    clearIcon: clearIcon,
    onTap: onTap,
    controller: controller,
    keyboardType: keyboardType,
    validator: validator,
    autoValidate: autoValidate ?? false,
    hintStyle: hintStyle,
    labelStyle: labelStyle,
    counterStyle: counterStyle,
    errorStyle: errorStyle,
    textStyle: textStyle,
    helperStyle: helperStyle,
    inputFormatter: inputFormatter,
    onFocusChange: onFocusChange,
    textInputAction: textInputAction,
    onFieldSubmitted: onFieldSubmitted,
    onSaved: onSaved,
    maxLength: maxLength,
    maxLines: maxLines,
    minLines: minLines,
    errorMaxLines: errorMaxLines,
    helperMaxLines: helperMaxLines,
    focusNode: focusNode,
    onClearText: onClearText,
    textInputKey: textInputKey,
    toolbarOptions: toolbarOptions,
    onEditingComplete: onEditingComplete,
    contentPadding: contentPadding,
    cursorColor: cursorColor,
    counterPadding: counterPadding,
    backgroundColor: backgroundColor,
  );

  factory FinfulTextInput.single({
    Key? key,
    bool autoFocus = false,
    bool enableInteractiveSelection = true,
    bool autocorrect = true,
    bool obscureText = false,
    bool enabled = true,
    bool showClearButton = true,
    required String hintText,
    String? labelText,
    String? helperText,
    String? errorText,
    String? initialValue,
    TextStyle? hintStyle,
    TextStyle? labelStyle,
    TextStyle? counterStyle,
    TextStyle? errorStyle,
    TextStyle? textStyle,
    TextStyle? helperStyle,
    ValueChanged<String>? onChanged,
    Widget? prefixIcon,
    Widget? suffixIcon,
    Widget? clearIcon,
    VoidCallback? onTap,
    TextEditingController? controller,
    TextInputType? keyboardType,
    FormFieldValidator<String>? validator,
    bool? autoValidate,
    List<TextInputFormatter>? inputFormatter,
    Function(bool hasFocus)? onFocusChange,
    TextInputAction? textInputAction,
    Function(String text)? onFieldSubmitted,
    Function(String?)? onSaved,
    int? maxLength,
    int? errorMaxLines,
    int? helperMaxLines,
    FocusNode? focusNode,
    VoidCallback? onClearText,
    ValueKey? textInputKey,
    ToolbarOptions? toolbarOptions,
    VoidCallback? onEditingComplete,
    EdgeInsets? contentPadding,
    Color? cursorColor,
    EdgeInsets? counterPadding,
    Color? backgroundColor,
    FinfulTextInputHeight height = FinfulTextInputHeight.sm,
  }) {
    return FinfulTextInput(
      key: key,
      autoFocus: autoFocus,
      enableInteractiveSelection: enableInteractiveSelection,
      autocorrect: autocorrect,
      obscureText: obscureText,
      enabled: enabled,
      showClearButton: showClearButton,
      hintText: hintText,
      labelText: labelText,
      helperText: helperText,
      errorText: errorText,
      initialValue: initialValue,
      onChanged: onChanged,
      prefixIcon: prefixIcon,
      suffixIcon: suffixIcon,
      clearIcon: clearIcon ??
          const Padding(
            padding: EdgeInsets.only(
              right: Dimens.p_16,
            ),
            child: Icon(
              Icons.clear,
              size: FinfulDimens.iconMd,
            ),
          ),
      onTap: onTap,
      controller: controller,
      keyboardType: keyboardType,
      validator: validator,
      autoValidate: autoValidate,
      hintStyle: _kHintStyle,
      labelStyle: enabled ? _kLabelStyle : _kDisabledLabelStyle,
      counterStyle: _kCounterStyle,
      errorStyle: _kErrorStyle,
      textStyle: enabled ? _kTextStyle : _kDisabledTextStyle,
      inputFormatter: inputFormatter,
      onFocusChange: onFocusChange,
      textInputAction: textInputAction,
      onFieldSubmitted: onFieldSubmitted,
      onSaved: onSaved,
      maxLength: maxLength,
      maxLines: 1,
      minLines: 1,
      errorMaxLines: errorMaxLines,
      helperMaxLines: helperMaxLines,
      focusNode: focusNode,
      onClearText: onClearText,
      textInputKey: textInputKey,
      toolbarOptions: toolbarOptions,
      onEditingComplete: onEditingComplete,
      contentPadding: contentPadding ??
          (height == FinfulTextInputHeight.sm ? smPadding : mdPadding),
      cursorColor: cursorColor,
      counterPadding: counterPadding,
      backgroundColor: enabled ? (backgroundColor ?? _kBgColor) : _kDisabledBgColor,
    );
  }

  factory FinfulTextInput.multiline({
    Key? key,
    bool autoFocus = false,
    bool enableInteractiveSelection = true,
    bool autocorrect = true,
    bool enabled = true,
    bool showClearButton = false,
    bool isBare = false,
    required int maxLines,
    required int minLines,
    required String hintText,
    String? helperText,
    String? errorText,
    String? initialValue,
    TextStyle? hintStyle,
    TextStyle? counterStyle,
    TextStyle? errorStyle,
    TextStyle? textStyle,
    TextStyle? helperStyle,
    ValueChanged<String>? onChanged,
    VoidCallback? onTap,
    TextEditingController? controller,
    TextInputType? keyboardType,
    FormFieldValidator<String>? validator,
    bool? autoValidate,
    List<TextInputFormatter>? inputFormatter,
    Function(bool hasFocus)? onFocusChange,
    TextInputAction? textInputAction,
    Function(String text)? onFieldSubmitted,
    Function(String?)? onSaved,
    int? maxLength,
    int? errorMaxLines,
    int? helperMaxLines,
    FocusNode? focusNode,
    ValueKey? textInputKey,
    ToolbarOptions? toolbarOptions,
    VoidCallback? onEditingComplete,
    EdgeInsets? contentPadding,
    Color? cursorColor,
    EdgeInsets? counterPadding,
    Color? backgroundColor,
  }) {
    return FinfulTextInput(
      key: key,
      autoFocus: autoFocus,
      enableInteractiveSelection: enableInteractiveSelection,
      autocorrect: autocorrect,
      obscureText: false,
      enabled: enabled,
      showClearButton: showClearButton,
      hintText: hintText,
      helperText: helperText,
      errorText: errorText,
      initialValue: initialValue,
      onChanged: onChanged,
      onTap: onTap,
      controller: controller,
      keyboardType: keyboardType,
      validator: validator,
      autoValidate: autoValidate,
      hintStyle: _kHintStyle,
      counterStyle: _kCounterStyle,
      errorStyle: _kErrorStyle,
      helperStyle: _kHelperStyle,
      textStyle: enabled ? _kTextStyle : _kDisabledTextStyle,
      inputFormatter: inputFormatter,
      onFocusChange: onFocusChange,
      textInputAction: textInputAction,
      onFieldSubmitted: onFieldSubmitted,
      onSaved: onSaved,
      maxLength: maxLength,
      maxLines: maxLines,
      minLines: minLines,
      errorMaxLines: errorMaxLines,
      helperMaxLines: helperMaxLines,
      focusNode: focusNode,
      textInputKey: textInputKey,
      toolbarOptions: toolbarOptions,
      onEditingComplete: onEditingComplete,
      contentPadding: contentPadding,
      cursorColor: cursorColor,
      counterPadding: counterPadding,
      backgroundColor: enabled ? (backgroundColor ?? _kBgColor) : _kDisabledBgColor,
      isBare: isBare,
    );
  }
}
